### ISSUE TITLE
[🐛 BUG]: Build with Velox failing [problem with incorrect host go.buf.build]

### ISSUE THREAD

**Issue by loperd** [roadrunner-server/roadrunner#1729]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

Hello! I can't build roadrunner with velox because I have a problem with it.

A log log line which says me what's happened: 
```
195.9 {"level":"debug","ts":1694898397.604284,"msg":"[STDERR OUTPUT]","log":"go: github.com/roadrunner-server/roadrunner/v2023/internal/cli/jobs imports\n\tgo.buf.build/protocolbuffers/go/roadrunner-server/api/jobs/v1: cannot find module providing package go.buf.build/protocolbuffers/go/roadrunner-server/api/jobs/v1: unrecognized import path \"go.buf.build/protocolbuffers/go/roadrunner-server/api/jobs\": https fetch: Get \"https://go.buf.build/protocolbuffers/go/roadrunner-server/api/jobs?go-get=1\": dial tcp: lookup go.buf.build on <FILTERED>:53: no such host\n"}
```

This is because go.mod contains the wrong host go.buf.build, with the wrong url now
```go
module github.com/roadrunner-server/roadrunner/v2023

go 1.20

require (
....
	**go.buf.build**/protocolbuffers/go/roadrunner-server/api v1.3.40
....
)

exclude github.com/uber-go/tally/v4 v4.1.7

require (
....
	**go.buf.build**/grpc/go/roadrunner-server/api v1.4.40 // indirect
....
)
```

### Version (rr --version)

2023.2.0

### How to reproduce the issue?

Build roadrunner v2023 with velox

### Relevant log output

```shell
https://pastebin.com/nrLVKRFK
```

**Comment by rustatian** [comment]
Hey @loperd 👋🏻 
Unfortunately, Buf removed their API for downloading Go dependencies. This solution has broken many libraries, including RR. I've moved the RR API proto to GitHub; however, you'll need to use the `master` (this is safe) branch for RR until I release `2023.3`: https://github.com/roadrunner-server/velox/blob/master/velox_rr_v2023.toml#L5

**Comment by loperd** [comment]
Thank you 🙏🏻

**Comment by rustatian** [comment]
I'll leave this ticket open, should be auto-resolved when `2023.3` is released.

**Comment by rustatian** [comment]
@loperd Resolved by `v2023.3.0`. Velox configuration file updated: [link](https://github.com/roadrunner-server/velox/blob/master/velox_rr_v2023.toml#L9)

**Comment by touqeershafi** [comment]
I'm still getting the same error even though I'm using latest toml
```
{"log": "go: github.com/roadrunner-server/roadrunner/v2023/container imports\n\tgithub.com/roadrunner-server/service/v4 imports\n\tgo.buf.build/protocolbuffers/go/roadrunner-server/api/service/v1: unrecognized import path \"go.buf.build/protocolbuffers/go/roadrunner-server/api\": https fetch: Get \"https://go.buf.build/protocolbuffers/go/roadrunner-server/api?go-get=1\": dial tcp: lookup go.buf.build: no such host\ngo: github.com/roadrunner-server/roadrunner/v2023/container imports\n\tgithub.com/roadrunner-server/service/v4 imports\n\tgo.buf.build/protocolbuffers/go/roadrunner-server/api/shared/v1: unrecognized import path \"go.buf.build/protocolbuffers/go/roadrunner-server/api\": https fetch: Get \"https://go.buf.build/protocolbuffers/go/roadrunner-server/api?go-get=1\": dial tcp: lookup go.buf.build: no such host\n"}
```

```
[velox]
build_args = [
    '-trimpath',
    '-ldflags',
    '-s -X github.com/roadrunner-server/roadrunner/v2023/internal/meta.version=${VERSION} -X github.com/roadrunner-server/roadrunner/v2023/internal/meta.buildTime=${TIME}'
]

[roadrunner]
ref = "v2023.3.12"

[github]
[github.token]
token = "xxxxx"

[github.plugins]
# LOGS


# HTTP + MIDDLEWARE
http = { ref = "v4.1.4", owner = "roadrunner-server", repository = "http" }
gzip = { ref = "v4.0.4", owner = "roadrunner-server", repository = "gzip" }
# SERVER
server = { ref = "v4.1.1", owner = "roadrunner-server", repository = "server" }
# SERVICE aka lightweit systemd
service = { ref = "v4.1.0", owner = "roadrunner-server", repository = "service" }
# TCP for the RAW TCP PAYLOADS
tcp = { ref = "v4.0.4", owner = "roadrunner-server", repository = "tcp" }


[log]
level = "debug"
mode = "development"
```

**Comment by rustatian** [comment]
Hey @touqeershafi 👋 
Please update plugins to their latest versions.
